language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-26
    - extra-android-support
    - extra-android-m2repository
  
before_install:
  - chmod +x gradlew
  - git submodule update --init --recursive
install:
  - ./gradlew
script:
  - ./gradlew :app:assembleDebug --stacktrace
  - ./gradlew :app:test --stacktrace
